import type { Metadata } from "next";
import type { ReactNode } from "react";

import { DocsCode, DocsOrigin } from "@/components/docs-code";
import { PageBreadcrumb } from "@/components/page-breadcrumb";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export const metadata: Metadata = {
  title: "API",
  description: "HTTP API reference for DisCloud.",
};

const methodVariant: Record<string, string> = {
  GET: "bg-geist-green-soft text-geist-green",
  HEAD: "bg-geist-blue-soft text-geist-blue",
  POST: "bg-geist-amber-soft text-geist-amber",
  PATCH: "bg-geist-purple-soft text-geist-purple",
  DELETE: "bg-geist-red-soft text-geist-red",
};

const tabs = [
  { id: "base", label: "Base URL" },
  { id: "cli", label: "CLI" },
  { id: "auth", label: "Auth" },
  { id: "upload", label: "Upload" },
  { id: "chunked", label: "Chunked" },
  { id: "download", label: "Download" },
  { id: "files", label: "Files" },
  { id: "ops", label: "Ops" },
  { id: "notes", label: "Notes" },
] as const;

function Method({ children }: { children: string }) {
  const parts = children.split("/");
  return (
    <span className="inline-flex flex-wrap gap-1">
      {parts.map((m) => (
        <Badge
          key={m}
          variant="secondary"
          className={`font-mono ${methodVariant[m] ?? ""}`}
        >
          {m}
        </Badge>
      ))}
    </span>
  );
}

function Endpoint({
  method,
  path,
  children,
}: {
  method: string;
  path: string;
  children: ReactNode;
}) {
  return (
    <article className="rounded-xl border border-border/60 bg-card/40 p-4 sm:p-5">
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <Method>{method}</Method>
        <code className="font-mono text-sm font-semibold break-all">{path}</code>
      </div>
      <div className="flex flex-col gap-3 text-sm text-muted-foreground [&_strong]:font-medium [&_strong]:text-foreground [&_code]:rounded [&_code]:bg-muted/60 [&_code]:px-1 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-[0.8rem] [&_code]:text-foreground">
        {children}
      </div>
    </article>
  );
}

function SectionLabel({ children }: { children: ReactNode }) {
  return (
    <p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
      {children}
    </p>
  );
}

function SectionIntro({
  title,
  children,
}: {
  title: string;
  children?: ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1">
      <h2 className="text-lg font-semibold tracking-tight">{title}</h2>
      {children ? (
        <p className="text-sm text-muted-foreground">{children}</p>
      ) : null}
    </div>
  );
}

export default function DocsPage() {
  return (
    <div className="flex flex-col gap-6">
      <PageBreadcrumb items={[{ label: "API" }]} />

      <header className="flex flex-col gap-2">
        <h1 className="text-2xl font-semibold tracking-tight">API reference</h1>
        <p className="max-w-2xl text-sm text-muted-foreground">
          Plain HTTP. Optional username/password sessions (
          <code className="font-mono text-foreground">discloud_session</code>
          ). Browser clients must send credentials and match{" "}
          <code className="font-mono text-foreground">WEB_ORIGIN</code>.
        </p>
      </header>

      <Tabs defaultValue="base" className="gap-6">
        <div className="-mx-1 overflow-x-auto overflow-y-hidden px-1 pb-1">
          <TabsList
            variant="line"
            className="h-auto w-max min-w-full justify-start gap-0"
          >
            {tabs.map((tab) => (
              <TabsTrigger
                key={tab.id}
                value={tab.id}
                className="flex-none px-3"
              >
                {tab.label}
              </TabsTrigger>
            ))}
          </TabsList>
        </div>

        <TabsContent value="base" className="flex flex-col gap-3">
          <SectionIntro title="Base URL">
            API origin (from <code className="font-mono text-foreground">API_URL</code>
            ): <DocsOrigin />
          </SectionIntro>
          <DocsCode>{`export BASE=$BASE`}</DocsCode>
        </TabsContent>

        <TabsContent value="cli" className="flex flex-col gap-4">
          <SectionIntro title="CLI">
            Install <code className="font-mono text-foreground">discloud-cli</code>{" "}
            (alias <code className="font-mono text-foreground">discloud</code>
            ). Scripts are generated by this API with{" "}
            <code className="font-mono text-foreground">DISCLOUD_BASE</code> /{" "}
            <code className="font-mono text-foreground">DISCLOUD_ORIGIN</code>{" "}
            baked from <code className="font-mono text-foreground">API_URL</code>{" "}
            and <code className="font-mono text-foreground">WEB_ORIGIN</code>;
            install writes them to the CLI config file (env still overrides).
          </SectionIntro>
          <SectionLabel>Install · macOS / Linux</SectionLabel>
          <DocsCode>{`curl -fsSL $WEB/install.sh | sh
# pin: DISCLOUD_VERSION=v0.1.0 curl -fsSL $WEB/install.sh | sh
# (or API directly: curl -fsSL $BASE/install.sh | sh)`}</DocsCode>
          <SectionLabel>Install · Windows (PowerShell)</SectionLabel>
          <DocsCode>{`irm $WEB/install.ps1 | iex`}</DocsCode>
          <SectionLabel>Scoop / Homebrew</SectionLabel>
          <DocsCode>{`scoop bucket add mew https://github.com/mewisme/scoop-mew
scoop install mew/discloud-cli

brew tap mewisme/mew
brew install --cask discloud-cli`}</DocsCode>
          <SectionLabel>Examples</SectionLabel>
          <DocsCode>{`discloud auth signin you secret123
discloud upload ./video.mp4          # resumable, 8 MB chunks
discloud files list
discloud get <id> --download --out video.mp4
discloud config                     # show base / origin / cookie path`}</DocsCode>
          <p className="text-sm text-muted-foreground">
            UI origin proxies installers (
            <code className="font-mono text-foreground">$WEB/install.sh</code>
            → API). Scripts still bake{" "}
            <code className="font-mono text-foreground">DISCLOUD_BASE</code> /{" "}
            <code className="font-mono text-foreground">DISCLOUD_ORIGIN</code>{" "}
            from the API. After install,{" "}
            <code className="font-mono text-foreground">discloud</code> and{" "}
            <code className="font-mono text-foreground">discloud-cli</code> are
            the same binary. The API server binary in Docker remains{" "}
            <code className="font-mono text-foreground">/discloud</code> and is
            separate.
          </p>
        </TabsContent>

        <TabsContent value="auth" className="flex flex-col gap-4">
          <SectionIntro title="Auth">
            Cookie session. Username is immutable after signup (3–32 chars,{" "}
            <code>[a-z0-9][a-z0-9_-]*</code>). First signup on a fresh DB
            becomes <code>admin</code>; later accounts are <code>user</code>.
            Password min 8 chars.
          </SectionIntro>

          <Endpoint method="POST" path="/api/auth/signup">
            <DocsCode>{`curl -X POST -H "Content-Type: application/json" -H "Origin: http://localhost:3000" \\
  -c cookies.txt -d '{"username":"you","password":"secret123"}' \\
  "$BASE/api/auth/signup"
# → { "id", "username", "role" } + Set-Cookie: discloud_session=…`}</DocsCode>
          </Endpoint>

          <Endpoint method="POST" path="/api/auth/signin">
            <p>Same body as signup. Invalid credentials → 401.</p>
            <DocsCode>{`curl -X POST -H "Content-Type: application/json" -H "Origin: http://localhost:3000" \\
  -c cookies.txt -d '{"username":"you","password":"secret123"}' \\
  "$BASE/api/auth/signin"`}</DocsCode>
          </Endpoint>

          <Endpoint method="POST" path="/api/auth/signout">
            <p>Clears the session cookie. 204.</p>
            <DocsCode>{`curl -X POST -H "Origin: http://localhost:3000" -b cookies.txt \\
  "$BASE/api/auth/signout"`}</DocsCode>
          </Endpoint>

          <Endpoint method="GET" path="/api/auth/me">
            <p>
              Account dashboard payload: identity, file stats, current session
              metadata, and retention constants. 401 if not signed in. Touches
              session <code>lastSeenAt</code>.
            </p>
            <DocsCode>{`curl -s -b cookies.txt "$BASE/api/auth/me"
# → {
#   "id", "username", "role", "createdAt", "passwordChangedAt",
#   "stats": { "fileCount", "totalBytes", "publicCount", "privateCount", "expiringSoonCount" },
#   "session": { "createdAt", "lastSeenAt", "expiresAt", "ip", "userAgent" },
#   "retention": { "authenticatedDays", "anonymousDays", "downloadExtensionDays", "maxRetentionDays" }
# }`}</DocsCode>
          </Endpoint>

          <Endpoint method="POST" path="/api/auth/password">
            <p>
              Requires session. Body:{" "}
              <code>{`{"currentPassword","newPassword"}`}</code>. 204. Other
              sessions stay valid.
            </p>
            <DocsCode>{`curl -X POST -H "Content-Type: application/json" -H "Origin: http://localhost:3000" \\
  -b cookies.txt -d '{"currentPassword":"secret123","newPassword":"secret456"}' \\
  "$BASE/api/auth/password"`}</DocsCode>
          </Endpoint>
        </TabsContent>

        <TabsContent value="upload" className="flex flex-col gap-4">
          <SectionIntro title="Upload">
            One request for small/medium files. Body = raw bytes. Server splits
            into 8&nbsp;MB chunks. Public by default. With a session cookie,
            the file is owned (30-day retention); anonymous = 7 days.
          </SectionIntro>

          <Endpoint method="POST" path="/api/upload?fileName={name}">
            <p>
              Simplest path when proxies allow the whole body (e.g. Cloudflare
              caps at ~100&nbsp;MB — use chunked upload for larger files).
            </p>
            <SectionLabel>Example</SectionLabel>
            <DocsCode>{`curl -X POST --data-binary @video.mp4 \\
  "$BASE/api/upload?fileName=video.mp4"`}</DocsCode>
            <SectionLabel>Response · 200</SectionLabel>
            <DocsCode>{`{
  "fileId": "894d9eec70b09280134933c50b168592",
  "fileName": "video.mp4",
  "fileSize": 10485760,
  "chunkSize": 8388608,
  "visibility": "public",
  "ownedByCurrentUser": false,
  "createdAt": "…",
  "expiresAt": "…",
  "url": "$BASE/f/894d9eec…",
  "longURL": "$BASE/f/894d9eec…/video.mp4",
  "downloadURL": "$BASE/f/894d9eec…?download=1",
  "longDownloadURL": "$BASE/f/894d9eec…/video.mp4?download=1"
}`}</DocsCode>
            <p>
              <strong>Errors:</strong> 400 if <code>fileName</code> is missing or
              the body is empty.
            </p>
          </Endpoint>
        </TabsContent>

        <TabsContent value="chunked" className="flex flex-col gap-4">
          <SectionIntro title="Chunked upload">
            Any size, resumable. Split into <strong>8&nbsp;MB</strong> pieces
            (last chunk may be shorter). Each chunk is keyed by SHA-256 — skip
            uploads the server already has. Send credentials on complete so
            ownership attaches when signed in.
          </SectionIntro>

          <Endpoint method="GET/HEAD" path="/api/chunks/{sha256}">
            <p>
              Check if a chunk exists. <strong>200</strong> = skip,{" "}
              <strong>404</strong> = upload it.
            </p>
            <DocsCode>{`curl -I "$BASE/api/chunks/<sha256>"`}</DocsCode>
          </Endpoint>

          <Endpoint method="POST" path="/api/chunks">
            <p>
              Upload one chunk (raw body, max 8&nbsp;MB). Hash is computed
              server-side. <code>existed: true</code> means it was already stored.
            </p>
            <DocsCode>{`curl -X POST --data-binary @part-aa "$BASE/api/chunks"
# → { "hash": "2af4eff9…", "existed": false }`}</DocsCode>
            <p>
              <strong>Errors:</strong> 400 empty body · 413 over 8&nbsp;MB.
            </p>
          </Endpoint>

          <Endpoint method="POST" path="/api/upload/complete">
            <p>Assemble chunks in order. Response matches single upload.</p>
            <DocsCode>{`curl -X POST -H "Content-Type: application/json" \\
  "$BASE/api/upload/complete" \\
  -d '{
    "fileName": "video.mp4",
    "chunkHashes": ["<hash1>", "<hash2>"]
  }'`}</DocsCode>
            <SectionLabel>Bash · split + upload + complete</SectionLabel>
            <DocsCode>{`split -b 8m video.mp4 part-
hashes=()
for p in part-*; do
  hashes+=("$(curl -s -X POST --data-binary @"$p" \\
    "$BASE/api/chunks" | jq -r .hash)")
done
printf '%s\\n' "\${hashes[@]}" | jq -R . | jq -s \\
  '{fileName: "video.mp4", chunkHashes: .}' |
  curl -s -X POST -H "Content-Type: application/json" \\
    -d @- "$BASE/api/upload/complete"`}</DocsCode>
          </Endpoint>
        </TabsContent>

        <TabsContent value="download" className="flex flex-col gap-4">
          <SectionIntro title="Download">
            Stream bytes, force download, or fetch metadata. Single-chunk
            responses may redirect to the CDN. Private files need a session
            (owner/admin) or <code>?token=</code> / <code>X-File-Token</code>.
          </SectionIntro>

          <Endpoint method="GET" path="/f/{fileId}[/{fileName}]">
            <ul className="flex list-disc flex-col gap-1 pl-4">
              <li>
                Optional <code>{"/{fileName}"}</code> is cosmetic (nice share
                URLs).
              </li>
              <li>
                <code>?download=1</code> → attachment disposition; extends
                retention (not HEAD, not Range)
              </li>
              <li>
                <code>?json=1</code> → metadata JSON (no file bytes)
              </li>
              <li>
                <code>?token=</code> → private file access token
              </li>
              <li>
                <code>Range</code> → 206; open-ended ranges capped at 5&nbsp;MB
              </li>
            </ul>
            <DocsCode>{`curl -OJ "$BASE/f/<id>/video.mp4?download=1"
curl -s "$BASE/f/<id>?json=1"
curl -H "Range: bytes=0-1023" "$BASE/f/<id>"
curl -s "$BASE/f/<id>?token=<accessToken>&json=1"`}</DocsCode>
            <p>
              <strong>Errors:</strong> 404 unknown / expired / unauthorized
              private · 416 bad range.
            </p>
          </Endpoint>
        </TabsContent>

        <TabsContent value="files" className="flex flex-col gap-4">
          <SectionIntro title="Files & inspect" />

          <Endpoint method="GET" path="/api/files">
            <p>
              <strong>Auth required.</strong> Files owned by the current user
              (paginated <code>limit</code>/<code>offset</code>).
            </p>
            <DocsCode>{`curl -s -b cookies.txt "$BASE/api/files"
# { "files": [{ "fileId", "fileName", "visibility", "expiresAt", … }] }`}</DocsCode>
          </Endpoint>

          <Endpoint method="GET" path="/api/files/{fileId}">
            <p>
              One file’s metadata. Private: owner/admin session or token. 404 if
              unknown / denied / expired.
            </p>
            <DocsCode>{`curl -s "$BASE/api/files/<id>"
curl -s "$BASE/api/files/<id>?token=<accessToken>"`}</DocsCode>
          </Endpoint>

          <Endpoint method="GET" path="/api/files/{fileId}/inspect">
            <p>
              Analytics (views, downloads, ranges, bytes served, unique visitors)
              plus share URLs. Same authz as metadata. UI:{" "}
              <code>/i/{"{fileId}"}</code>.
            </p>
            <DocsCode>{`curl -s "$BASE/api/files/<id>/inspect"`}</DocsCode>
          </Endpoint>

          <Endpoint method="PATCH" path="/api/files/{fileId}/visibility">
            <p>
              Owner or admin. Body:{" "}
              <code>{`{ "visibility": "public" | "private" }`}</code>. Private
              returns a one-time <code>accessToken</code> (shown once — rotate to
              recover). Anonymous-owned files cannot go private (403). Public
              clears the token.
            </p>
            <DocsCode>{`curl -X PATCH -H "Content-Type: application/json" -H "Origin: http://localhost:3000" \\
  -b cookies.txt -d '{"visibility":"private"}' \\
  "$BASE/api/files/<id>/visibility"
# → { "visibility": "private", "accessToken": "…" }`}</DocsCode>
          </Endpoint>

          <Endpoint method="POST" path="/api/files/{fileId}/access-token/rotate">
            <p>
              Owner or admin; private files only. Returns a new one-time{" "}
              <code>accessToken</code>; old token stops working.
            </p>
            <DocsCode>{`curl -X POST -H "Origin: http://localhost:3000" -b cookies.txt \\
  "$BASE/api/files/<id>/access-token/rotate"`}</DocsCode>
          </Endpoint>

          <Endpoint method="DELETE" path="/api/files/{fileId}">
            <p>
              Owner or admin. <strong>204</strong>. Deletes Postgres metadata
              only — Discord attachments are untouched. File tokens cannot
              delete.
            </p>
            <DocsCode>{`curl -X DELETE -H "Origin: http://localhost:3000" -b cookies.txt \\
  "$BASE/api/files/<id>"`}</DocsCode>
          </Endpoint>

          <Endpoint method="GET" path="/api/info">
            <p>
              Public config for clients: bot/worker hint and chunk size.
            </p>
            <DocsCode>{`curl -s "$BASE/api/info"
# { "bots": 1, "chunkSize": 8388608, "workers": 3 }`}</DocsCode>
          </Endpoint>
        </TabsContent>

        <TabsContent value="ops" className="flex flex-col gap-4">
          <SectionIntro title="Ops" />

          <Endpoint method="GET" path="/healthz">
            <p>Liveness. Always 200 if the process is up.</p>
            <DocsCode>{`curl -s "$BASE/healthz"   # ok`}</DocsCode>
          </Endpoint>

          <Endpoint method="GET" path="/readyz">
            <p>
              Readiness: 200 when Postgres + Valkey are reachable, else 503. The
              UI polls this for the degraded banner.
            </p>
            <DocsCode>{`curl -s -o /dev/null -w "%{http_code}\\n" "$BASE/readyz"`}</DocsCode>
          </Endpoint>
        </TabsContent>

        <TabsContent value="notes" className="flex flex-col gap-3 pb-6">
          <SectionIntro title="Notes" />
          <ul className="flex list-disc flex-col gap-2 pl-5 text-sm text-muted-foreground">
            <li>
              Errors are JSON:{" "}
              <code className="font-mono text-foreground">{`{ "message": "…" }`}</code>
            </li>
            <li>
              File names are kebab-cased (
              <code className="font-mono text-foreground">My File (1).PDF</code>{" "}
              → <code className="font-mono text-foreground">my-file-1.pdf</code>
              )
            </li>
            <li>
              CDN URLs are refreshed on download so share links stay valid
            </li>
            <li>
              CORS allowlists exact <code className="font-mono text-foreground">WEB_ORIGIN</code>{" "}
              with credentials. Mutating requests with a session cookie (or with
              an <code>Origin</code> header) must match that origin.
            </li>
            <li>
              <code className="font-mono text-foreground">SameSite=Lax</code> cookies
              need API + UI same-site (path proxy in prod; localhost ports OK).
            </li>
            <li>
              Retention: anonymous 7d, authenticated 30d;{" "}
              <code>?download=1</code> extends by 7d (cap 30d from now). Cleanup
              deletes expired Postgres rows only.
            </li>
            <li>
              Private denials are uniform <strong>404</strong> (no existence leak).
              Token-authenticated responses set{" "}
              <code>Referrer-Policy: no-referrer</code>.
            </li>
          </ul>
        </TabsContent>
      </Tabs>
    </div>
  );
}
