#!/bin/sh
#
# discloud-cli installer (macOS / Linux) — generated by this DisCloud API.
#
# curl -fsSL {{DISCLOUD_BASE}}/install.sh | sh
#
# Uninstall: sh install.sh --uninstall
#
# Environment:
#   DISCLOUD_VERSION      release tag (default: latest)
#   DISCLOUD_INSTALL_DIR  bundle location (default: ~/.discloud)
#   DISCLOUD_BIN_DIR      symlink location (default: ~/.local/bin)
#   DISCLOUD_BASE / DISCLOUD_ORIGIN override the defaults baked in below.
set -eu

REPO="mewisme/discloud-go"
INSTALL_DIR="${DISCLOUD_INSTALL_DIR:-$HOME/.discloud}"
BIN_DIR="${DISCLOUD_BIN_DIR:-$HOME/.local/bin}"

# Defaults from the API that served this script (API_URL / WEB_ORIGIN).
DEFAULT_DISCLOUD_BASE="{{DISCLOUD_BASE}}"
DEFAULT_DISCLOUD_ORIGIN="{{DISCLOUD_ORIGIN}}"

if [ "${1:-}" = "--uninstall" ]; then
  rm -f "$BIN_DIR/discloud-cli" "$BIN_DIR/discloud"
  rm -rf "$INSTALL_DIR"
  echo "discloud-cli uninstalled (removed $INSTALL_DIR and $BIN_DIR/discloud{,-cli})."
  exit 0
fi

os="$(uname -s)"
arch="$(uname -m)"
case "$os" in
  Darwin) os="darwin" ;;
  Linux) os="linux" ;;
  *) echo "discloud-cli: unsupported OS '$os'." >&2; exit 1 ;;
esac
case "$arch" in
  arm64|aarch64) arch="arm64" ;;
  x86_64|amd64) arch="amd64" ;;
  *) echo "discloud-cli: unsupported architecture '$arch'." >&2; exit 1 ;;
esac

version="${DISCLOUD_VERSION:-}"
if [ -z "$version" ]; then
  version="$(curl -fsSLI -o /dev/null -w '%{url_effective}' "https://github.com/$REPO/releases/latest" \
    | sed -n 's#.*/releases/tag/##p')"
fi
if [ -z "$version" ]; then
  version="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
    | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -n1)"
fi
[ -n "$version" ] || {
  echo "discloud-cli: could not resolve latest version; set DISCLOUD_VERSION (e.g. DISCLOUD_VERSION=v0.1.0)." >&2
  exit 1
}
case "$version" in v*) ;; *) version="v$version" ;; esac
ver="${version#v}"

url="https://github.com/$REPO/releases/download/$version/discloud-cli_${ver}_${os}_${arch}.tar.gz"
echo "Installing discloud-cli $version ($os/$arch)..."
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
curl -fsSL "$url" -o "$tmp/discloud-cli.tar.gz" || {
  echo "discloud-cli: download failed: $url" >&2
  exit 1
}

dest="$INSTALL_DIR/versions/$version"
rm -rf "$dest"
mkdir -p "$dest"
tar -xzf "$tmp/discloud-cli.tar.gz" -C "$dest"
chmod +x "$dest/discloud-cli"

mkdir -p "$BIN_DIR"
ln -sf "$dest/discloud-cli" "$BIN_DIR/discloud-cli"
ln -sf "$dest/discloud-cli" "$BIN_DIR/discloud"
ln -sfn "$dest" "$INSTALL_DIR/current"

# Prune older versions.
if [ -d "$INSTALL_DIR/versions" ]; then
  for d in "$INSTALL_DIR/versions"/*; do
    [ -d "$d" ] || continue
    [ "$d" = "$dest" ] || rm -rf "$d"
  done
fi

# Persist API defaults for the CLI (env still wins when set).
cfg_dir="${XDG_CONFIG_HOME:-$HOME/.config}/discloud"
mkdir -p "$cfg_dir"
base_out="${DISCLOUD_BASE:-$DEFAULT_DISCLOUD_BASE}"
origin_out="${DISCLOUD_ORIGIN:-$DEFAULT_DISCLOUD_ORIGIN}"
cat > "$cfg_dir/config.json" <<EOF
{"base":"$base_out","origin":"$origin_out"}
EOF
echo "Wrote $cfg_dir/config.json (base=$base_out origin=$origin_out)"

echo "Installed to $dest"
echo "Linked $BIN_DIR/discloud-cli"
echo "Linked $BIN_DIR/discloud (alias)"

on_path=0
oldifs="$IFS"
IFS=:
for dir in $PATH; do
  [ "$dir" = "$BIN_DIR" ] && on_path=1 && break
done
IFS="$oldifs"

if [ "$on_path" -eq 0 ]; then
  echo ""
  echo "$BIN_DIR is not on your PATH. Add it:"
  echo "  export PATH=\"$BIN_DIR:\$PATH\""
fi

echo ""
echo "Done. Run: discloud version   # or: discloud-cli version"
